services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app # 로컬 코드 수정 시 실시간 반영(Hot Reload)
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/traivldb
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg16
    container_name: traivl-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: traivldb
    ports:
      - "5432:5432"
    volumes:
      - traivl-db-data:/var/lib/postgresql/data # DB 데이터 영구 저장

volumes:
  traivl-db-data:
